# Generated by Django 4.2.4 on 2023-09-07 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_alter_brandmodel_user'),
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsemodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_response', to='brands.brandmodel'),
        ),
    ]
