# Generated by Django 4.2.5 on 2025-07-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_alter_responsemodel_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsemodel',
            name='response',
            field=models.JSONField(default=dict),
        ),
    ]
