# Generated by Django 4.2.4 on 2023-09-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='brand_name',
            field=models.CharField(default='My Brand', max_length=50),
        ),
        migrations.AddField(
            model_name='brandmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
