# Generated by Django 4.2.4 on 2023-09-06 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0002_brandmodel_brand_name_brandmodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
