# Generated by Django 4.2.4 on 2023-09-07 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0003_alter_brandmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
