# Generated by Django 4.2.4 on 2023-09-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_alter_brandmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmodel',
            name='brand_name',
            field=models.CharField(default='My Brand', max_length=50, unique=True),
        ),
    ]
