# Generated by Django 4.2.4 on 2023-09-10 06:59

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_alter_brandmodel_brand_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandmodel',
            name='colors',
        ),
        migrations.AddField(
            model_name='brandmodel',
            name='color1',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='brandmodel',
            name='color2',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='brandmodel',
            name='color3',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='brandmodel',
            name='color4',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=25, null=True, samples=None),
        ),
    ]
