# Generated by Django 4.2.4 on 2023-09-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0007_alter_brandmodel_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmodel',
            name='font',
            field=models.CharField(choices=[('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Montserrat', 'Montserrat'), ('Poppins', 'Poppins'), ('Merriweather', 'Merriweather'), ('Raleway', 'Raleway'), ('Playfair Display', 'Playfair Display'), ('Source Sans Pro', 'Source Sans Pro'), ('Crimson Text', 'Crimson Text'), ('Nunito', 'Nunito'), ('Oswald', 'Oswald'), ('Quicksand', 'Quicksand'), ('Ubuntu', 'Ubuntu'), ('Inconsolata', 'Inconsolata'), ('Pacifico', 'Pacifico'), ('Dancing Script', 'Dancing Script'), ('Cabin', 'Cabin'), ('Bebas Neue', 'Bebas Neue'), ('Alegreya', 'Alegreya'), ('Arimo', 'Arimo'), ('Karla', 'Karla'), ('Fira Sans', 'Fira Sans'), ('Archivo', 'Archivo'), ('Cormorant Garamond', 'Cormorant Garamond')], max_length=300),
        ),
    ]
