# Generated by Django 5.2.4 on 2025-07-20 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0008_alter_brandmodel_font'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandmodel',
            name='color1',
        ),
        migrations.RemoveField(
            model_name='brandmodel',
            name='color2',
        ),
        migrations.RemoveField(
            model_name='brandmodel',
            name='color3',
        ),
        migrations.RemoveField(
            model_name='brandmodel',
            name='color4',
        ),
        migrations.RemoveField(
            model_name='brandmodel',
            name='font',
        ),
    ]
