# Generated by Django 4.2.4 on 2023-09-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=300)),
                ('file', models.FileField(null=True, upload_to='contacts')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
