# Generated by Django 4.2.4 on 2023-09-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='file',
            field=models.FileField(null=True, upload_to='contacts/'),
        ),
    ]
